
namespace Dodoco.Core.Game;

public enum GameVoiceManagerState {

    IDLE,
    RECOVERING_DOWNLOADED_VOICE_PACKAGE,
    DOWNLOADING_VOICE_PACKAGE,
    UNZIPPING_VOICE_PACKAGE,
    DOWNLOADING_VOICE_PACKAGE_UPDATE,
    UNZIPPING_VOICE_PACKAGE_UPDATE,
    APPLYING_VOICE_PACKAGE_UPDATE,
    REMOVING_DEPRECATED_FILES

}